// Package "ticks" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version v0.29.0 DO NOT EDIT.
package ticks

import (
	"context"
	"fmt"

	"github.com/lerenn/asyncapi-codegen/pkg/extensions"

	"github.com/google/uuid"
)

// UserSubscriber represents all handlers that are expecting messages for User
type UserSubscriber interface {
	// WatchTicks subscribes to messages placed on the 'cryptellation.ticks.live.{exchange}.{pair}' channel
	WatchTicks(ctx context.Context, msg TickMessage)

	// RegisterToTicksResponse subscribes to messages placed on the 'cryptellation.ticks.register.response' channel
	RegisterToTicksResponse(ctx context.Context, msg RegisteringResponseMessage)

	// ServiceInfoResponse subscribes to messages placed on the 'cryptellation.ticks.service.info.response' channel
	ServiceInfoResponse(ctx context.Context, msg ServiceInfoResponseMessage)

	// UnregisterToTicksResponse subscribes to messages placed on the 'cryptellation.ticks.unregister.response' channel
	UnregisterToTicksResponse(ctx context.Context, msg RegisteringResponseMessage)
}

// UserController is the structure that provides publishing capabilities to the
// developer and and connect the broker with the User
type UserController struct {
	controller
}

// NewUserController links the User to the broker
func NewUserController(bc extensions.BrokerController, options ...ControllerOption) (*UserController, error) {
	// Check if broker controller has been provided
	if bc == nil {
		return nil, extensions.ErrNilBrokerController
	}

	// Create default controller
	controller := controller{
		broker:        bc,
		subscriptions: make(map[string]extensions.BrokerChannelSubscription),
		logger:        extensions.DummyLogger{},
		middlewares:   make([]extensions.Middleware, 0),
	}

	// Apply options
	for _, option := range options {
		option(&controller)
	}

	return &UserController{controller: controller}, nil
}

func (c UserController) wrapMiddlewares(
	middlewares []extensions.Middleware,
	callback extensions.NextMiddleware,
) func(ctx context.Context, msg *extensions.BrokerMessage) error {
	var called bool

	// If there is no more middleware
	if len(middlewares) == 0 {
		return func(ctx context.Context, msg *extensions.BrokerMessage) error {
			// Call the callback if it exists and it has not been called already
			if callback != nil && !called {
				called = true
				return callback(ctx)
			}

			// Nil can be returned, as the callback has already been called
			return nil
		}
	}

	// Get the next function to call from next middlewares or callback
	next := c.wrapMiddlewares(middlewares[1:], callback)

	// Wrap middleware into a check function that will call execute the middleware
	// and call the next wrapped middleware if the returned function has not been
	// called already
	return func(ctx context.Context, msg *extensions.BrokerMessage) error {
		// Call the middleware and the following if it has not been done already
		if !called {
			// Create the next call with the context and the message
			nextWithArgs := func(ctx context.Context) error {
				return next(ctx, msg)
			}

			// Call the middleware and register it as already called
			called = true
			if err := middlewares[0](ctx, msg, nextWithArgs); err != nil {
				return err
			}

			// If next has already been called in middleware, it should not be executed again
			return nextWithArgs(ctx)
		}

		// Nil can be returned, as the next middleware has already been called
		return nil
	}
}

func (c UserController) executeMiddlewares(ctx context.Context, msg *extensions.BrokerMessage, callback extensions.NextMiddleware) error {
	// Wrap middleware to have 'next' function when calling them
	wrapped := c.wrapMiddlewares(c.middlewares, callback)

	// Execute wrapped middlewares
	return wrapped(ctx, msg)
}

func addUserContextValues(ctx context.Context, path string) context.Context {
	ctx = context.WithValue(ctx, extensions.ContextKeyIsVersion, "1.0.0")
	ctx = context.WithValue(ctx, extensions.ContextKeyIsProvider, "user")
	return context.WithValue(ctx, extensions.ContextKeyIsChannel, path)
}

// Close will clean up any existing resources on the controller
func (c *UserController) Close(ctx context.Context) {
	// Unsubscribing remaining channels
	c.UnsubscribeAll(ctx)

	c.logger.Info(ctx, "Closed user controller")
}

// SubscribeAll will subscribe to channels without parameters on which the app is expecting messages.
// For channels with parameters, they should be subscribed independently.
func (c *UserController) SubscribeAll(ctx context.Context, as UserSubscriber) error {
	if as == nil {
		return extensions.ErrNilUserSubscriber
	}

	if err := c.SubscribeRegisterToTicksResponse(ctx, as.RegisterToTicksResponse); err != nil {
		return err
	}
	if err := c.SubscribeServiceInfoResponse(ctx, as.ServiceInfoResponse); err != nil {
		return err
	}
	if err := c.SubscribeUnregisterToTicksResponse(ctx, as.UnregisterToTicksResponse); err != nil {
		return err
	}

	return nil
}

// UnsubscribeAll will unsubscribe all remaining subscribed channels
func (c *UserController) UnsubscribeAll(ctx context.Context) {
	c.UnsubscribeRegisterToTicksResponse(ctx)
	c.UnsubscribeServiceInfoResponse(ctx)
	c.UnsubscribeUnregisterToTicksResponse(ctx)
}

// SubscribeWatchTicks will subscribe to new messages from 'cryptellation.ticks.live.{exchange}.{pair}' channel.
//
// Callback function 'fn' will be called each time a new message is received.
func (c *UserController) SubscribeWatchTicks(ctx context.Context, params CryptellationTicksLiveParameters, fn func(ctx context.Context, msg TickMessage)) error {
	// Get channel path
	path := fmt.Sprintf("cryptellation.ticks.live.%v.%v", params.Exchange, params.Pair)

	// Set context
	ctx = addUserContextValues(ctx, path)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "reception")

	// Check if there is already a subscription
	_, exists := c.subscriptions[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", extensions.ErrAlreadySubscribedChannel, path)
		c.logger.Error(ctx, err.Error())
		return err
	}

	// Subscribe to broker channel
	sub, err := c.broker.Subscribe(ctx, path)
	if err != nil {
		c.logger.Error(ctx, err.Error())
		return err
	}
	c.logger.Info(ctx, "Subscribed to channel")

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			brokerMsg, open := <-sub.MessagesChannel()

			// If subscription is closed and there is no more message
			// (i.e. uninitialized message), then exit the function
			if !open && brokerMsg.IsUninitialized() {
				return
			}

			// Set broker message to context
			ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

			// Execute middlewares before handling the message
			if err := c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
				// Process message
				msg, err := newTickMessageFromBrokerMessage(brokerMsg)
				if err != nil {
					return err
				}

				// Execute the subscription function
				fn(ctx, msg)

				return nil
			}); err != nil {
				c.logger.Error(ctx, err.Error())
			}
		}
	}()

	// Add the cancel channel to the inside map
	c.subscriptions[path] = sub

	return nil
}

// UnsubscribeWatchTicks will unsubscribe messages from 'cryptellation.ticks.live.{exchange}.{pair}' channel.
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *UserController) UnsubscribeWatchTicks(ctx context.Context, params CryptellationTicksLiveParameters) {
	// Get channel path
	path := fmt.Sprintf("cryptellation.ticks.live.%v.%v", params.Exchange, params.Pair)

	// Check if there subscribers for this channel
	sub, exists := c.subscriptions[path]
	if !exists {
		return
	}

	// Set context
	ctx = addUserContextValues(ctx, path)

	// Stop the subscription
	sub.Cancel(ctx)

	// Remove if from the subscribers
	delete(c.subscriptions, path)

	c.logger.Info(ctx, "Unsubscribed from channel")
} // SubscribeRegisterToTicksResponse will subscribe to new messages from 'cryptellation.ticks.register.response' channel.
// Callback function 'fn' will be called each time a new message is received.
func (c *UserController) SubscribeRegisterToTicksResponse(ctx context.Context, fn func(ctx context.Context, msg RegisteringResponseMessage)) error {
	// Get channel path
	path := "cryptellation.ticks.register.response"

	// Set context
	ctx = addUserContextValues(ctx, path)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "reception")

	// Check if there is already a subscription
	_, exists := c.subscriptions[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", extensions.ErrAlreadySubscribedChannel, path)
		c.logger.Error(ctx, err.Error())
		return err
	}

	// Subscribe to broker channel
	sub, err := c.broker.Subscribe(ctx, path)
	if err != nil {
		c.logger.Error(ctx, err.Error())
		return err
	}
	c.logger.Info(ctx, "Subscribed to channel")

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			brokerMsg, open := <-sub.MessagesChannel()

			// If subscription is closed and there is no more message
			// (i.e. uninitialized message), then exit the function
			if !open && brokerMsg.IsUninitialized() {
				return
			}

			// Set broker message to context
			ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

			// Execute middlewares before handling the message
			if err := c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
				// Process message
				msg, err := newRegisteringResponseMessageFromBrokerMessage(brokerMsg)
				if err != nil {
					return err
				}

				// Add correlation ID to context if it exists
				if id := msg.CorrelationID(); id != "" {
					ctx = context.WithValue(ctx, extensions.ContextKeyIsCorrelationID, id)
				}

				// Execute the subscription function
				fn(ctx, msg)

				return nil
			}); err != nil {
				c.logger.Error(ctx, err.Error())
			}
		}
	}()

	// Add the cancel channel to the inside map
	c.subscriptions[path] = sub

	return nil
}

// UnsubscribeRegisterToTicksResponse will unsubscribe messages from 'cryptellation.ticks.register.response' channel.
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *UserController) UnsubscribeRegisterToTicksResponse(ctx context.Context) {
	// Get channel path
	path := "cryptellation.ticks.register.response"

	// Check if there subscribers for this channel
	sub, exists := c.subscriptions[path]
	if !exists {
		return
	}

	// Set context
	ctx = addUserContextValues(ctx, path)

	// Stop the subscription
	sub.Cancel(ctx)

	// Remove if from the subscribers
	delete(c.subscriptions, path)

	c.logger.Info(ctx, "Unsubscribed from channel")
} // SubscribeServiceInfoResponse will subscribe to new messages from 'cryptellation.ticks.service.info.response' channel.
// Callback function 'fn' will be called each time a new message is received.
func (c *UserController) SubscribeServiceInfoResponse(ctx context.Context, fn func(ctx context.Context, msg ServiceInfoResponseMessage)) error {
	// Get channel path
	path := "cryptellation.ticks.service.info.response"

	// Set context
	ctx = addUserContextValues(ctx, path)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "reception")

	// Check if there is already a subscription
	_, exists := c.subscriptions[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", extensions.ErrAlreadySubscribedChannel, path)
		c.logger.Error(ctx, err.Error())
		return err
	}

	// Subscribe to broker channel
	sub, err := c.broker.Subscribe(ctx, path)
	if err != nil {
		c.logger.Error(ctx, err.Error())
		return err
	}
	c.logger.Info(ctx, "Subscribed to channel")

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			brokerMsg, open := <-sub.MessagesChannel()

			// If subscription is closed and there is no more message
			// (i.e. uninitialized message), then exit the function
			if !open && brokerMsg.IsUninitialized() {
				return
			}

			// Set broker message to context
			ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

			// Execute middlewares before handling the message
			if err := c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
				// Process message
				msg, err := newServiceInfoResponseMessageFromBrokerMessage(brokerMsg)
				if err != nil {
					return err
				}

				// Add correlation ID to context if it exists
				if id := msg.CorrelationID(); id != "" {
					ctx = context.WithValue(ctx, extensions.ContextKeyIsCorrelationID, id)
				}

				// Execute the subscription function
				fn(ctx, msg)

				return nil
			}); err != nil {
				c.logger.Error(ctx, err.Error())
			}
		}
	}()

	// Add the cancel channel to the inside map
	c.subscriptions[path] = sub

	return nil
}

// UnsubscribeServiceInfoResponse will unsubscribe messages from 'cryptellation.ticks.service.info.response' channel.
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *UserController) UnsubscribeServiceInfoResponse(ctx context.Context) {
	// Get channel path
	path := "cryptellation.ticks.service.info.response"

	// Check if there subscribers for this channel
	sub, exists := c.subscriptions[path]
	if !exists {
		return
	}

	// Set context
	ctx = addUserContextValues(ctx, path)

	// Stop the subscription
	sub.Cancel(ctx)

	// Remove if from the subscribers
	delete(c.subscriptions, path)

	c.logger.Info(ctx, "Unsubscribed from channel")
} // SubscribeUnregisterToTicksResponse will subscribe to new messages from 'cryptellation.ticks.unregister.response' channel.
// Callback function 'fn' will be called each time a new message is received.
func (c *UserController) SubscribeUnregisterToTicksResponse(ctx context.Context, fn func(ctx context.Context, msg RegisteringResponseMessage)) error {
	// Get channel path
	path := "cryptellation.ticks.unregister.response"

	// Set context
	ctx = addUserContextValues(ctx, path)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "reception")

	// Check if there is already a subscription
	_, exists := c.subscriptions[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", extensions.ErrAlreadySubscribedChannel, path)
		c.logger.Error(ctx, err.Error())
		return err
	}

	// Subscribe to broker channel
	sub, err := c.broker.Subscribe(ctx, path)
	if err != nil {
		c.logger.Error(ctx, err.Error())
		return err
	}
	c.logger.Info(ctx, "Subscribed to channel")

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			brokerMsg, open := <-sub.MessagesChannel()

			// If subscription is closed and there is no more message
			// (i.e. uninitialized message), then exit the function
			if !open && brokerMsg.IsUninitialized() {
				return
			}

			// Set broker message to context
			ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

			// Execute middlewares before handling the message
			if err := c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
				// Process message
				msg, err := newRegisteringResponseMessageFromBrokerMessage(brokerMsg)
				if err != nil {
					return err
				}

				// Add correlation ID to context if it exists
				if id := msg.CorrelationID(); id != "" {
					ctx = context.WithValue(ctx, extensions.ContextKeyIsCorrelationID, id)
				}

				// Execute the subscription function
				fn(ctx, msg)

				return nil
			}); err != nil {
				c.logger.Error(ctx, err.Error())
			}
		}
	}()

	// Add the cancel channel to the inside map
	c.subscriptions[path] = sub

	return nil
}

// UnsubscribeUnregisterToTicksResponse will unsubscribe messages from 'cryptellation.ticks.unregister.response' channel.
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *UserController) UnsubscribeUnregisterToTicksResponse(ctx context.Context) {
	// Get channel path
	path := "cryptellation.ticks.unregister.response"

	// Check if there subscribers for this channel
	sub, exists := c.subscriptions[path]
	if !exists {
		return
	}

	// Set context
	ctx = addUserContextValues(ctx, path)

	// Stop the subscription
	sub.Cancel(ctx)

	// Remove if from the subscribers
	delete(c.subscriptions, path)

	c.logger.Info(ctx, "Unsubscribed from channel")
}

// PublishRegisterToTicksRequest will publish messages to 'cryptellation.ticks.register.request' channel
func (c *UserController) PublishRegisterToTicksRequest(ctx context.Context, msg RegisteringRequestMessage) error {
	// Get channel path
	path := "cryptellation.ticks.register.request"

	// Set correlation ID if it does not exist
	if id := msg.CorrelationID(); id == "" {
		msg.SetCorrelationID(uuid.New().String())
	}

	// Set context
	ctx = addUserContextValues(ctx, path)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "publication")
	ctx = context.WithValue(ctx, extensions.ContextKeyIsCorrelationID, msg.CorrelationID())

	// Convert to BrokerMessage
	brokerMsg, err := msg.toBrokerMessage()
	if err != nil {
		return err
	}

	// Set broker message to context
	ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

	// Publish the message on event-broker through middlewares
	return c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
		return c.broker.Publish(ctx, path, brokerMsg)
	})
}

// PublishServiceInfoRequest will publish messages to 'cryptellation.ticks.service.info.request' channel
func (c *UserController) PublishServiceInfoRequest(ctx context.Context, msg ServiceInfoRequestMessage) error {
	// Get channel path
	path := "cryptellation.ticks.service.info.request"

	// Set correlation ID if it does not exist
	if id := msg.CorrelationID(); id == "" {
		msg.SetCorrelationID(uuid.New().String())
	}

	// Set context
	ctx = addUserContextValues(ctx, path)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "publication")
	ctx = context.WithValue(ctx, extensions.ContextKeyIsCorrelationID, msg.CorrelationID())

	// Convert to BrokerMessage
	brokerMsg, err := msg.toBrokerMessage()
	if err != nil {
		return err
	}

	// Set broker message to context
	ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

	// Publish the message on event-broker through middlewares
	return c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
		return c.broker.Publish(ctx, path, brokerMsg)
	})
}

// PublishUnregisterToTicksRequest will publish messages to 'cryptellation.ticks.unregister.request' channel
func (c *UserController) PublishUnregisterToTicksRequest(ctx context.Context, msg RegisteringRequestMessage) error {
	// Get channel path
	path := "cryptellation.ticks.unregister.request"

	// Set correlation ID if it does not exist
	if id := msg.CorrelationID(); id == "" {
		msg.SetCorrelationID(uuid.New().String())
	}

	// Set context
	ctx = addUserContextValues(ctx, path)
	ctx = context.WithValue(ctx, extensions.ContextKeyIsDirection, "publication")
	ctx = context.WithValue(ctx, extensions.ContextKeyIsCorrelationID, msg.CorrelationID())

	// Convert to BrokerMessage
	brokerMsg, err := msg.toBrokerMessage()
	if err != nil {
		return err
	}

	// Set broker message to context
	ctx = context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())

	// Publish the message on event-broker through middlewares
	return c.executeMiddlewares(ctx, &brokerMsg, func(ctx context.Context) error {
		return c.broker.Publish(ctx, path, brokerMsg)
	})
}

// WaitForRegisterToTicksResponse will wait for a specific message by its correlation ID.
//
// The pub function is the publication function that should be used to send the message.
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message.
//
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *UserController) WaitForRegisterToTicksResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func(ctx context.Context) error) (RegisteringResponseMessage, error) {
	// Get channel path
	path := "cryptellation.ticks.register.response"

	// Set context
	ctx = addUserContextValues(ctx, path)

	// Subscribe to broker channel
	sub, err := c.broker.Subscribe(ctx, path)
	if err != nil {
		c.logger.Error(ctx, err.Error())
		return RegisteringResponseMessage{}, err
	}
	c.logger.Info(ctx, "Subscribed to channel")

	// Close subscriber on leave
	defer func() {
		// Stop the subscription
		sub.Cancel(ctx)

		// Logging unsubscribing
		c.logger.Info(ctx, "Unsubscribed from channel")
	}()

	// Execute callback for publication
	if err = pub(ctx); err != nil {
		return RegisteringResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case brokerMsg, open := <-sub.MessagesChannel():
			// If subscription is closed and there is no more message
			// (i.e. uninitialized message), then the subscription ended before
			// receiving the expected message
			if !open && brokerMsg.IsUninitialized() {
				c.logger.Error(ctx, "Channel closed before getting message")
				return RegisteringResponseMessage{}, extensions.ErrSubscriptionCanceled
			}

			// Get new message
			msg, err := newRegisteringResponseMessageFromBrokerMessage(brokerMsg)
			if err != nil {
				c.logger.Error(ctx, err.Error())
			}

			// If message doesn't have corresponding correlation ID, then continue
			if publishMsg.CorrelationID() != msg.CorrelationID() {
				continue
			}

			// Set context with received values as it is the expected message
			msgCtx := context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())
			msgCtx = context.WithValue(msgCtx, extensions.ContextKeyIsDirection, "reception")
			msgCtx = context.WithValue(msgCtx, extensions.ContextKeyIsCorrelationID, publishMsg.CorrelationID())

			// Execute middlewares before returning
			if err := c.executeMiddlewares(msgCtx, &brokerMsg, nil); err != nil {
				return RegisteringResponseMessage{}, err
			}

			// Return the message to the caller from the broker that could have
			// been modified by middlewares
			return newRegisteringResponseMessageFromBrokerMessage(brokerMsg)
		case <-ctx.Done(): // Set corrsponding error if context is done
			c.logger.Error(ctx, "Context done before getting message")
			return RegisteringResponseMessage{}, extensions.ErrContextCanceled
		}
	}
}

// WaitForServiceInfoResponse will wait for a specific message by its correlation ID.
//
// The pub function is the publication function that should be used to send the message.
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message.
//
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *UserController) WaitForServiceInfoResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func(ctx context.Context) error) (ServiceInfoResponseMessage, error) {
	// Get channel path
	path := "cryptellation.ticks.service.info.response"

	// Set context
	ctx = addUserContextValues(ctx, path)

	// Subscribe to broker channel
	sub, err := c.broker.Subscribe(ctx, path)
	if err != nil {
		c.logger.Error(ctx, err.Error())
		return ServiceInfoResponseMessage{}, err
	}
	c.logger.Info(ctx, "Subscribed to channel")

	// Close subscriber on leave
	defer func() {
		// Stop the subscription
		sub.Cancel(ctx)

		// Logging unsubscribing
		c.logger.Info(ctx, "Unsubscribed from channel")
	}()

	// Execute callback for publication
	if err = pub(ctx); err != nil {
		return ServiceInfoResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case brokerMsg, open := <-sub.MessagesChannel():
			// If subscription is closed and there is no more message
			// (i.e. uninitialized message), then the subscription ended before
			// receiving the expected message
			if !open && brokerMsg.IsUninitialized() {
				c.logger.Error(ctx, "Channel closed before getting message")
				return ServiceInfoResponseMessage{}, extensions.ErrSubscriptionCanceled
			}

			// Get new message
			msg, err := newServiceInfoResponseMessageFromBrokerMessage(brokerMsg)
			if err != nil {
				c.logger.Error(ctx, err.Error())
			}

			// If message doesn't have corresponding correlation ID, then continue
			if publishMsg.CorrelationID() != msg.CorrelationID() {
				continue
			}

			// Set context with received values as it is the expected message
			msgCtx := context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())
			msgCtx = context.WithValue(msgCtx, extensions.ContextKeyIsDirection, "reception")
			msgCtx = context.WithValue(msgCtx, extensions.ContextKeyIsCorrelationID, publishMsg.CorrelationID())

			// Execute middlewares before returning
			if err := c.executeMiddlewares(msgCtx, &brokerMsg, nil); err != nil {
				return ServiceInfoResponseMessage{}, err
			}

			// Return the message to the caller from the broker that could have
			// been modified by middlewares
			return newServiceInfoResponseMessageFromBrokerMessage(brokerMsg)
		case <-ctx.Done(): // Set corrsponding error if context is done
			c.logger.Error(ctx, "Context done before getting message")
			return ServiceInfoResponseMessage{}, extensions.ErrContextCanceled
		}
	}
}

// WaitForUnregisterToTicksResponse will wait for a specific message by its correlation ID.
//
// The pub function is the publication function that should be used to send the message.
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message.
//
// A timeout can be set in context to avoid blocking operation, if needed.
func (c *UserController) WaitForUnregisterToTicksResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func(ctx context.Context) error) (RegisteringResponseMessage, error) {
	// Get channel path
	path := "cryptellation.ticks.unregister.response"

	// Set context
	ctx = addUserContextValues(ctx, path)

	// Subscribe to broker channel
	sub, err := c.broker.Subscribe(ctx, path)
	if err != nil {
		c.logger.Error(ctx, err.Error())
		return RegisteringResponseMessage{}, err
	}
	c.logger.Info(ctx, "Subscribed to channel")

	// Close subscriber on leave
	defer func() {
		// Stop the subscription
		sub.Cancel(ctx)

		// Logging unsubscribing
		c.logger.Info(ctx, "Unsubscribed from channel")
	}()

	// Execute callback for publication
	if err = pub(ctx); err != nil {
		return RegisteringResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case brokerMsg, open := <-sub.MessagesChannel():
			// If subscription is closed and there is no more message
			// (i.e. uninitialized message), then the subscription ended before
			// receiving the expected message
			if !open && brokerMsg.IsUninitialized() {
				c.logger.Error(ctx, "Channel closed before getting message")
				return RegisteringResponseMessage{}, extensions.ErrSubscriptionCanceled
			}

			// Get new message
			msg, err := newRegisteringResponseMessageFromBrokerMessage(brokerMsg)
			if err != nil {
				c.logger.Error(ctx, err.Error())
			}

			// If message doesn't have corresponding correlation ID, then continue
			if publishMsg.CorrelationID() != msg.CorrelationID() {
				continue
			}

			// Set context with received values as it is the expected message
			msgCtx := context.WithValue(ctx, extensions.ContextKeyIsBrokerMessage, brokerMsg.String())
			msgCtx = context.WithValue(msgCtx, extensions.ContextKeyIsDirection, "reception")
			msgCtx = context.WithValue(msgCtx, extensions.ContextKeyIsCorrelationID, publishMsg.CorrelationID())

			// Execute middlewares before returning
			if err := c.executeMiddlewares(msgCtx, &brokerMsg, nil); err != nil {
				return RegisteringResponseMessage{}, err
			}

			// Return the message to the caller from the broker that could have
			// been modified by middlewares
			return newRegisteringResponseMessageFromBrokerMessage(brokerMsg)
		case <-ctx.Done(): // Set corrsponding error if context is done
			c.logger.Error(ctx, "Context done before getting message")
			return RegisteringResponseMessage{}, extensions.ErrContextCanceled
		}
	}
}
