# Specific section for dependencies

cockroachdb:
  enabled: true
  tls:
    enabled: false
temporal:
  enabled: true
  admintools:
    enabled: false
  server:
    config:
      persistence:
        default:
          driver: "sql"
          sql:
            driver: "postgres12"
            host: "cryptellation-cockroachdb-public"
            port: 26257
            user: "temporal"
            password: "nopasswordneeded"
            database: "temporal"
        visibility:
          driver: "sql"
          sql:
            driver: "postgres12"
            host: "cryptellation-cockroachdb-public"
            port: 26257
            user: "temporal"
            password: "nopasswordneeded"
            database: "temporal"
      namespaces:
        create: true
    replicaCount: 1
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false

# Specific section for credentials
credentials:
  exchanges:
    binance:
      api_key:
      secret_key:
  datastores:
    sql:
      database: cryptellation
      host: "{{ .Release.Name }}-cockroachdb-public.{{ .Release.Namespace }}.svc.cluster.local"
      port: 26257
      user: cryptellation
      password: cryptellation
  opentelemetry:
    grpc:
      endpoint:
  temporal:
    address: "{{ .Release.Name }}-temporal-frontend.{{ .Release.Namespace }}.svc.cluster.local:7233"

# Specific section for services
services:
  worker:
    image:
      repository: lerenn/cryptellation
      tag: v{{ .Chart.AppVersion }}
      pullPolicy: Always
    health:
      port: 9000

# Specific section for debug

debug:
  forceDeployment: false
