apiVersion: v1
kind: ConfigMap
metadata:
    name: cryptellation-config
data:
    # Worker
    worker.mongodb.database: "{{ (((.Values.services).worker).mongodb).database | default "cryptellation" }}"
    worker.health.port: "{{ (((.Values.services).worker).health).port | default 9000 }}"
