apiVersion: v1
kind: ConfigMap
metadata:
    name: cryptellation-config
data:
    # Worker
    worker.sql.database: "{{ (((.Values.services).worker).sql).database | default "cryptellation" }}"
    worker.health.port: "{{ (((.Values.services).worker).health).port | default 9000 }}"
