apiVersion: v1
kind: ConfigMap
metadata:
    name: cryptellation-config
data:
    health.port: "{{ .Values.config.health.port | default 9000 }}"
    nats.host: "{{ .Values.config.nats.host }}"
    nats.port: "{{ .Values.config.nats.port }}"
    sql.host: "{{ .Values.config.sql.host }}"
    sql.port: "{{ .Values.config.sql.port }}"
