apiVersion: v1
kind: ConfigMap
metadata:
    name: cryptellation-credentials
data:
    # Exchanges
    binance.api_key: "{{ (.Values.credentials).exchanges.binance.api_key }}"
    binance.secret_key: "{{ (.Values.credentials).exchanges.binance.secret_key }}"
    
    # Temporal
    {{ $DEFAULT_TEMPORAL_ADDRESS := (print "temporal." .Release.Namespace ".svc.cluster.local:7233") }}
    temporal.address: "{{ ((.Values.credentials).temporal).address | default $DEFAULT_TEMPORAL_ADDRESS }}"

    # Datastores
    {{ $DEFAULT_MONGODB_CONNECTION_STRING := (print "mongodb://" .Release.Name "-mongodb." .Release.Namespace ".svc.cluster.local:27017") }}
    mongodb.connection_string: "{{ ((.Values.credentials).datastores).mongodb.connection_string | default $DEFAULT_MONGODB_CONNECTION_STRING }}"

    # Opentelemetry
    opentelemetry.grpc.endpoint: "{{ ((.Values.credentials).opentelemetry).grpc.endpoint }}"
