apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-ui
  ports:
    - name: http
      protocol: TCP
      port: 8080