receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    send_batch_size: 10000
    timeout: 100ms

exporters:
  otlp/uptrace:
    endpoint: http://uptrace:4317
    tls:
      insecure: true
    headers:
      uptrace-dsn: 'http://cryptellation_secret_token@localhost:4318?grpc=4317'

service:
  telemetry:
    logs:
      level: DEBUG
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: ["otlp/uptrace"]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: ["otlp/uptrace"]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: ["otlp/uptrace"]