################################################################################
# Dependencies
################################################################################

cockroachdb:
  enabled: true
  tls:
    enabled: false
temporal:
  enabled: true
  admintools:
    enabled: false
  server:
    config:
      persistence:
        default:
          driver: "sql"
          sql:
            driver: "postgres12"
            host: "cryptellation-cockroachdb-public"
            port: 26257
            user: "temporal"
            password: "nopasswordneeded"
            database: "temporal"
        visibility:
          driver: "sql"
          sql:
            driver: "postgres12"
            host: "cryptellation-cockroachdb-public"
            port: 26257
            user: "temporal"
            password: "nopasswordneeded"
            database: "temporal"
      namespaces:
        create: true
    replicaCount: 1
  cassandra:
    enabled: false
  elasticsearch:
    enabled: false
  prometheus:
    enabled: false
  grafana:
    enabled: false

################################################################################
# Credentials
################################################################################

credentials:
  exchanges:
    binance:
      api_key:
      secret_key:
  opentelemetry:
    grpc:
      endpoint: otel-collector-opentelemetry-collector.telemetry.svc.cluster.local:4317

################################################################################
# Services
################################################################################

services:
  gateway:
    image:
      tag: devel
      pullPolicy: Never
  worker:
    image:
      tag: devel
      pullPolicy: Never

################################################################################
# Debug
################################################################################

debug:
  forceDeployment: true
