################################################################################
# Dependencies
################################################################################

mongodb:
  enabled: true

temporal:
  enabled: true

################################################################################
# Credentials
################################################################################

credentials:
  exchanges:
    binance:
      api_key:
      secret_key:
  opentelemetry:
    grpc:
      endpoint: otel-collector-opentelemetry-collector.telemetry.svc.cluster.local:4317

################################################################################
# Services
################################################################################

services:
  worker:
    image:
      tag: devel
      pullPolicy: Never

################################################################################
# Debug
################################################################################

debug:
  forceDeployment: true
