{{- if .Values.cockroachdb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-init-databases
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: cockroachdb-init-databases
    spec:
      containers:
      - name: cockroachdb-init-databases
        image: cockroachdb/cockroach:v22.2.2
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /init
            name: cockroachdb-init-scripts-volume
        command:
          - sh
          - /init/entrypoint.sh
      volumes:
      - name: cockroachdb-init-scripts-volume
        configMap:
          name: cockroachdb-init-scripts
      restartPolicy: Never
{{- end}}
