// Package "internal" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version (devel) DO NOT EDIT.
package internal

import (
	"context"
	"fmt"
)

// ClientSubscriber represents all handlers that are expecting messages for Client
type ClientSubscriber interface {
	// CandlesticksListResponse
	CandlesticksListResponse(msg CandlesticksListResponseMessage)
}

// ClientController is the structure that provides publishing capabilities to the
// developer and and connect the broker with the Client
type ClientController struct {
	brokerController BrokerController
	stopSubscribers  map[string]chan interface{}
	errChan          chan Error
}

// NewClientController links the Client to the broker
func NewClientController(bs BrokerController) (*ClientController, error) {
	if bs == nil {
		return nil, ErrNilBrokerController
	}

	return &ClientController{
		brokerController: bs,
		stopSubscribers:  make(map[string]chan interface{}),
		errChan:          make(chan Error, 256),
	}, nil
}

// Errors will give back the channel that contains errors and that you can listen to handle errors
// Please take a look at Error struct form information on error
func (c ClientController) Errors() <-chan Error {
	return c.errChan
}

// Close will clean up any existing resources on the controller
func (c *ClientController) Close() {
	c.UnsubscribeAll()
	close(c.errChan)
}

// SubscribeAll will subscribe to channels on which the app is expecting messages
func (c *ClientController) SubscribeAll(as ClientSubscriber) error {
	if as == nil {
		return ErrNilClientSubscriber
	}

	if err := c.SubscribeCandlesticksListResponse(as.CandlesticksListResponse); err != nil {
		return err
	}

	return nil
}

// UnsubscribeAll will unsubscribe all remaining subscribed channels
func (c *ClientController) UnsubscribeAll() {
	c.UnsubscribeCandlesticksListResponse()
}

// SubscribeCandlesticksListResponse will subscribe to new messages from 'candlesticks.list.response' channel
func (c *ClientController) SubscribeCandlesticksListResponse(fn func(msg CandlesticksListResponseMessage)) error {
	// Check if there is already a subscription
	_, exists := c.stopSubscribers["candlesticks.list.response"]
	if exists {
		return fmt.Errorf("%w: candlesticks.list.response channel is already subscribed", ErrAlreadySubscribedChannel)
	}

	// Subscribe to broker channel
	msgs, stop, err := c.brokerController.Subscribe("candlesticks.list.response")
	if err != nil {
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for um, open := <-msgs; open; um, open = <-msgs {
			msg, err := newCandlesticksListResponseMessageFromUniversalMessage(um)
			if err != nil {
				c.handleError("candlesticks.list.response", err)
			} else {
				fn(msg)
			}
		}
	}()

	// Add the stop channel to the inside map
	c.stopSubscribers["candlesticks.list.response"] = stop

	return nil
}

// UnsubscribeCandlesticksListResponse will unsubscribe messages from 'candlesticks.list.response' channel
func (c *ClientController) UnsubscribeCandlesticksListResponse() {
	stopChan, exists := c.stopSubscribers["candlesticks.list.response"]
	if !exists {
		return
	}

	stopChan <- true
	delete(c.stopSubscribers, "candlesticks.list.response")
}

// PublishCandlesticksListRequest will publish messages to 'candlesticks.list.request' channel
func (c *ClientController) PublishCandlesticksListRequest(msg CandlesticksListRequestMessage) error {
	// Convert to UniversalMessage
	um, err := msg.toUniversalMessage()
	if err != nil {
		return err
	}

	// Publish on event broker
	return c.brokerController.Publish("candlesticks.list.request", um)
}

func (c *ClientController) handleError(channelName string, err error) {
	// Wrap error with the channel name
	errWrapped := Error{
		Channel: channelName,
		Err:     err,
	}

	// Send it to the error channel
	select {
	case c.errChan <- errWrapped:
	default:
		// Drop error if it's full or closed
	}
}

// WaitForCandlesticksListResponse will wait for a specific message by its correlation ID
//
// The pub function is the publication function that should be used to send the message
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message
func (cc *ClientController) WaitForCandlesticksListResponse(ctx context.Context, msg MessageWithCorrelationID, pub func() error) (CandlesticksListResponseMessage, error) {
	// Subscribe to broker channel
	msgs, stop, err := cc.brokerController.Subscribe("candlesticks.list.response")
	if err != nil {
		return CandlesticksListResponseMessage{}, err
	}

	// Close subscriber on leave
	defer func() { stop <- true }()

	// Execute publication
	if err := pub(); err != nil {
		return CandlesticksListResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case um := <-msgs:
			msg, err := newCandlesticksListResponseMessageFromUniversalMessage(um)
			if err != nil {
				cc.handleError("candlesticks.list.response", err)
				continue
			}

			if msg.Headers.CorrelationID != nil && msg.CorrelationID() == *msg.Headers.CorrelationID {
				return msg, nil
			}
		case <-ctx.Done(): // TODO: make it consumable between two call
			return CandlesticksListResponseMessage{}, ErrContextCancelled
		}
	}
}
