// Package "events" provides primitives to interact with the AsyncAPI specification.
//
// Code generated by github.com/lerenn/asyncapi-codegen version v0.15.0 DO NOT EDIT.
package events

import (
	"context"
	"fmt"

	"github.com/lerenn/asyncapi-codegen/pkg/log"
)

// ClientSubscriber represents all handlers that are expecting messages for Client
type ClientSubscriber interface {
	// CryptellationBacktestsAccountsListResponse
	CryptellationBacktestsAccountsListResponse(msg BacktestsAccountsListResponseMessage, done bool)

	// CryptellationBacktestsAdvanceResponse
	CryptellationBacktestsAdvanceResponse(msg BacktestsAdvanceResponseMessage, done bool)

	// CryptellationBacktestsCreateResponse
	CryptellationBacktestsCreateResponse(msg BacktestsCreateResponseMessage, done bool)

	// CryptellationBacktestsEventsID
	CryptellationBacktestsEventsID(msg BacktestsEventMessage, done bool)

	// CryptellationBacktestsOrdersCreateResponse
	CryptellationBacktestsOrdersCreateResponse(msg BacktestsOrdersCreateResponseMessage, done bool)

	// CryptellationBacktestsOrdersListResponse
	CryptellationBacktestsOrdersListResponse(msg BacktestsOrdersListResponseMessage, done bool)

	// CryptellationBacktestsSubscribeResponse
	CryptellationBacktestsSubscribeResponse(msg BacktestsSubscribeResponseMessage, done bool)
}

// ClientController is the structure that provides publishing capabilities to the
// developer and and connect the broker with the Client
type ClientController struct {
	brokerController BrokerController
	stopSubscribers  map[string]chan interface{}
	logger           log.Logger
}

// NewClientController links the Client to the broker
func NewClientController(bs BrokerController) (*ClientController, error) {
	if bs == nil {
		return nil, ErrNilBrokerController
	}

	return &ClientController{
		brokerController: bs,
		stopSubscribers:  make(map[string]chan interface{}),
		logger:           log.Silent{},
	}, nil
}

// SetLogger attaches a logger that will log operations on controller
func (c *ClientController) SetLogger(logger log.Logger) {
	c.logger = logger
	c.brokerController.SetLogger(logger)
}

// LogError logs error if the logger has been set
func (c ClientController) LogError(ctx log.Context, msg string) {
	// Add more context
	ctx.Module = "asyncapi"
	ctx.Provider = "client"

	// Log error
	c.logger.Error(ctx, msg)
}

// LogInfo logs information if the logger has been set
func (c ClientController) LogInfo(ctx log.Context, msg string) {
	// Add more context
	ctx.Module = "asyncapi"
	ctx.Provider = "client"

	// Log info
	c.logger.Info(ctx, msg)
}

// Close will clean up any existing resources on the controller
func (c *ClientController) Close() {
	// Unsubscribing remaining channels
	c.LogInfo(log.Context{}, "Closing Client controller")
	c.UnsubscribeAll()
}

// SubscribeAll will subscribe to channels without parameters on which the app is expecting messages.
// For channels with parameters, they should be subscribed independently.
func (c *ClientController) SubscribeAll(as ClientSubscriber) error {
	if as == nil {
		return ErrNilClientSubscriber
	}

	if err := c.SubscribeCryptellationBacktestsAccountsListResponse(as.CryptellationBacktestsAccountsListResponse); err != nil {
		return err
	}
	if err := c.SubscribeCryptellationBacktestsAdvanceResponse(as.CryptellationBacktestsAdvanceResponse); err != nil {
		return err
	}
	if err := c.SubscribeCryptellationBacktestsCreateResponse(as.CryptellationBacktestsCreateResponse); err != nil {
		return err
	}
	if err := c.SubscribeCryptellationBacktestsOrdersCreateResponse(as.CryptellationBacktestsOrdersCreateResponse); err != nil {
		return err
	}
	if err := c.SubscribeCryptellationBacktestsOrdersListResponse(as.CryptellationBacktestsOrdersListResponse); err != nil {
		return err
	}
	if err := c.SubscribeCryptellationBacktestsSubscribeResponse(as.CryptellationBacktestsSubscribeResponse); err != nil {
		return err
	}

	return nil
}

// UnsubscribeAll will unsubscribe all remaining subscribed channels
func (c *ClientController) UnsubscribeAll() {
	// Unsubscribe channels with no parameters (if any)
	c.UnsubscribeCryptellationBacktestsAccountsListResponse()
	c.UnsubscribeCryptellationBacktestsAdvanceResponse()
	c.UnsubscribeCryptellationBacktestsCreateResponse()
	c.UnsubscribeCryptellationBacktestsOrdersCreateResponse()
	c.UnsubscribeCryptellationBacktestsOrdersListResponse()
	c.UnsubscribeCryptellationBacktestsSubscribeResponse()

	// Unsubscribe remaining channels
	for n, stopChan := range c.stopSubscribers {
		stopChan <- true
		delete(c.stopSubscribers, n)
	}
}

// SubscribeCryptellationBacktestsAccountsListResponse will subscribe to new messages from 'cryptellation.backtests.accounts.list.response' channel.
//
// Callback function 'fn' will be called each time a new message is received.
// The 'done' argument indicates when the subscription is canceled and can be
// used to clean up resources.
func (c *ClientController) SubscribeCryptellationBacktestsAccountsListResponse(fn func(msg BacktestsAccountsListResponseMessage, done bool)) error {
	// Get channel path
	path := "cryptellation.backtests.accounts.list.response"

	// Check if there is already a subscription
	_, exists := c.stopSubscribers[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", ErrAlreadySubscribedChannel, path)
		c.LogError(log.Context{Action: path}, err.Error())
		return err
	}

	// Subscribe to broker channel
	c.LogInfo(log.Context{Action: path, Operation: "subscribe"}, "Subscribing to channel")
	msgs, stop, err := c.brokerController.Subscribe(path)
	if err != nil {
		c.LogError(log.Context{Action: path, Operation: "subscribe"}, err.Error())
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			um, open := <-msgs

			// Process message
			msg, err := newBacktestsAccountsListResponseMessageFromUniversalMessage(um)
			if err != nil {
				c.LogError(log.Context{Action: path, Operation: "subscribe", Message: msg}, err.Error())
			}

			// Send info if message is correct or susbcription is closed
			if err == nil || !open {
				c.LogInfo(log.Context{Action: path, Operation: "subscribe", Message: msg}, "Received new message")
				fn(msg, !open)
			}

			// If subscription is closed, then exit the function
			if !open {
				return
			}
		}
	}()

	// Add the stop channel to the inside map
	c.stopSubscribers[path] = stop

	return nil
}

// UnsubscribeCryptellationBacktestsAccountsListResponse will unsubscribe messages from 'cryptellation.backtests.accounts.list.response' channel
func (c *ClientController) UnsubscribeCryptellationBacktestsAccountsListResponse() {
	// Get channel path
	path := "cryptellation.backtests.accounts.list.response"

	// Get stop channel
	stopChan, exists := c.stopSubscribers[path]
	if !exists {
		return
	}

	// Stop the channel and remove the entry
	c.LogInfo(log.Context{Action: path, Operation: "unsubscribe"}, "Unsubscribing from channel")
	stopChan <- true
	delete(c.stopSubscribers, path)
} // SubscribeCryptellationBacktestsAdvanceResponse will subscribe to new messages from 'cryptellation.backtests.advance.response' channel.
// Callback function 'fn' will be called each time a new message is received.
// The 'done' argument indicates when the subscription is canceled and can be
// used to clean up resources.
func (c *ClientController) SubscribeCryptellationBacktestsAdvanceResponse(fn func(msg BacktestsAdvanceResponseMessage, done bool)) error {
	// Get channel path
	path := "cryptellation.backtests.advance.response"

	// Check if there is already a subscription
	_, exists := c.stopSubscribers[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", ErrAlreadySubscribedChannel, path)
		c.LogError(log.Context{Action: path}, err.Error())
		return err
	}

	// Subscribe to broker channel
	c.LogInfo(log.Context{Action: path, Operation: "subscribe"}, "Subscribing to channel")
	msgs, stop, err := c.brokerController.Subscribe(path)
	if err != nil {
		c.LogError(log.Context{Action: path, Operation: "subscribe"}, err.Error())
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			um, open := <-msgs

			// Process message
			msg, err := newBacktestsAdvanceResponseMessageFromUniversalMessage(um)
			if err != nil {
				c.LogError(log.Context{Action: path, Operation: "subscribe", Message: msg}, err.Error())
			}

			// Send info if message is correct or susbcription is closed
			if err == nil || !open {
				c.LogInfo(log.Context{Action: path, Operation: "subscribe", Message: msg}, "Received new message")
				fn(msg, !open)
			}

			// If subscription is closed, then exit the function
			if !open {
				return
			}
		}
	}()

	// Add the stop channel to the inside map
	c.stopSubscribers[path] = stop

	return nil
}

// UnsubscribeCryptellationBacktestsAdvanceResponse will unsubscribe messages from 'cryptellation.backtests.advance.response' channel
func (c *ClientController) UnsubscribeCryptellationBacktestsAdvanceResponse() {
	// Get channel path
	path := "cryptellation.backtests.advance.response"

	// Get stop channel
	stopChan, exists := c.stopSubscribers[path]
	if !exists {
		return
	}

	// Stop the channel and remove the entry
	c.LogInfo(log.Context{Action: path, Operation: "unsubscribe"}, "Unsubscribing from channel")
	stopChan <- true
	delete(c.stopSubscribers, path)
} // SubscribeCryptellationBacktestsCreateResponse will subscribe to new messages from 'cryptellation.backtests.create.response' channel.
// Callback function 'fn' will be called each time a new message is received.
// The 'done' argument indicates when the subscription is canceled and can be
// used to clean up resources.
func (c *ClientController) SubscribeCryptellationBacktestsCreateResponse(fn func(msg BacktestsCreateResponseMessage, done bool)) error {
	// Get channel path
	path := "cryptellation.backtests.create.response"

	// Check if there is already a subscription
	_, exists := c.stopSubscribers[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", ErrAlreadySubscribedChannel, path)
		c.LogError(log.Context{Action: path}, err.Error())
		return err
	}

	// Subscribe to broker channel
	c.LogInfo(log.Context{Action: path, Operation: "subscribe"}, "Subscribing to channel")
	msgs, stop, err := c.brokerController.Subscribe(path)
	if err != nil {
		c.LogError(log.Context{Action: path, Operation: "subscribe"}, err.Error())
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			um, open := <-msgs

			// Process message
			msg, err := newBacktestsCreateResponseMessageFromUniversalMessage(um)
			if err != nil {
				c.LogError(log.Context{Action: path, Operation: "subscribe", Message: msg}, err.Error())
			}

			// Send info if message is correct or susbcription is closed
			if err == nil || !open {
				c.LogInfo(log.Context{Action: path, Operation: "subscribe", Message: msg}, "Received new message")
				fn(msg, !open)
			}

			// If subscription is closed, then exit the function
			if !open {
				return
			}
		}
	}()

	// Add the stop channel to the inside map
	c.stopSubscribers[path] = stop

	return nil
}

// UnsubscribeCryptellationBacktestsCreateResponse will unsubscribe messages from 'cryptellation.backtests.create.response' channel
func (c *ClientController) UnsubscribeCryptellationBacktestsCreateResponse() {
	// Get channel path
	path := "cryptellation.backtests.create.response"

	// Get stop channel
	stopChan, exists := c.stopSubscribers[path]
	if !exists {
		return
	}

	// Stop the channel and remove the entry
	c.LogInfo(log.Context{Action: path, Operation: "unsubscribe"}, "Unsubscribing from channel")
	stopChan <- true
	delete(c.stopSubscribers, path)
} // SubscribeCryptellationBacktestsEventsID will subscribe to new messages from 'cryptellation.backtests.events.{id}' channel.
// Callback function 'fn' will be called each time a new message is received.
// The 'done' argument indicates when the subscription is canceled and can be
// used to clean up resources.
func (c *ClientController) SubscribeCryptellationBacktestsEventsID(params CryptellationBacktestsEventsIDParameters, fn func(msg BacktestsEventMessage, done bool)) error {
	// Get channel path
	path := fmt.Sprintf("cryptellation.backtests.events.%v", params.ID)

	// Check if there is already a subscription
	_, exists := c.stopSubscribers[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", ErrAlreadySubscribedChannel, path)
		c.LogError(log.Context{Action: path}, err.Error())
		return err
	}

	// Subscribe to broker channel
	c.LogInfo(log.Context{Action: path, Operation: "subscribe"}, "Subscribing to channel")
	msgs, stop, err := c.brokerController.Subscribe(path)
	if err != nil {
		c.LogError(log.Context{Action: path, Operation: "subscribe"}, err.Error())
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			um, open := <-msgs

			// Process message
			msg, err := newBacktestsEventMessageFromUniversalMessage(um)
			if err != nil {
				c.LogError(log.Context{Action: path, Operation: "subscribe", Message: msg}, err.Error())
			}

			// Send info if message is correct or susbcription is closed
			if err == nil || !open {
				c.LogInfo(log.Context{Action: path, Operation: "subscribe", Message: msg}, "Received new message")
				fn(msg, !open)
			}

			// If subscription is closed, then exit the function
			if !open {
				return
			}
		}
	}()

	// Add the stop channel to the inside map
	c.stopSubscribers[path] = stop

	return nil
}

// UnsubscribeCryptellationBacktestsEventsID will unsubscribe messages from 'cryptellation.backtests.events.{id}' channel
func (c *ClientController) UnsubscribeCryptellationBacktestsEventsID(params CryptellationBacktestsEventsIDParameters) {
	// Get channel path
	path := fmt.Sprintf("cryptellation.backtests.events.%v", params.ID)

	// Get stop channel
	stopChan, exists := c.stopSubscribers[path]
	if !exists {
		return
	}

	// Stop the channel and remove the entry
	c.LogInfo(log.Context{Action: path, Operation: "unsubscribe"}, "Unsubscribing from channel")
	stopChan <- true
	delete(c.stopSubscribers, path)
} // SubscribeCryptellationBacktestsOrdersCreateResponse will subscribe to new messages from 'cryptellation.backtests.orders.create.response' channel.
// Callback function 'fn' will be called each time a new message is received.
// The 'done' argument indicates when the subscription is canceled and can be
// used to clean up resources.
func (c *ClientController) SubscribeCryptellationBacktestsOrdersCreateResponse(fn func(msg BacktestsOrdersCreateResponseMessage, done bool)) error {
	// Get channel path
	path := "cryptellation.backtests.orders.create.response"

	// Check if there is already a subscription
	_, exists := c.stopSubscribers[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", ErrAlreadySubscribedChannel, path)
		c.LogError(log.Context{Action: path}, err.Error())
		return err
	}

	// Subscribe to broker channel
	c.LogInfo(log.Context{Action: path, Operation: "subscribe"}, "Subscribing to channel")
	msgs, stop, err := c.brokerController.Subscribe(path)
	if err != nil {
		c.LogError(log.Context{Action: path, Operation: "subscribe"}, err.Error())
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			um, open := <-msgs

			// Process message
			msg, err := newBacktestsOrdersCreateResponseMessageFromUniversalMessage(um)
			if err != nil {
				c.LogError(log.Context{Action: path, Operation: "subscribe", Message: msg}, err.Error())
			}

			// Send info if message is correct or susbcription is closed
			if err == nil || !open {
				c.LogInfo(log.Context{Action: path, Operation: "subscribe", Message: msg}, "Received new message")
				fn(msg, !open)
			}

			// If subscription is closed, then exit the function
			if !open {
				return
			}
		}
	}()

	// Add the stop channel to the inside map
	c.stopSubscribers[path] = stop

	return nil
}

// UnsubscribeCryptellationBacktestsOrdersCreateResponse will unsubscribe messages from 'cryptellation.backtests.orders.create.response' channel
func (c *ClientController) UnsubscribeCryptellationBacktestsOrdersCreateResponse() {
	// Get channel path
	path := "cryptellation.backtests.orders.create.response"

	// Get stop channel
	stopChan, exists := c.stopSubscribers[path]
	if !exists {
		return
	}

	// Stop the channel and remove the entry
	c.LogInfo(log.Context{Action: path, Operation: "unsubscribe"}, "Unsubscribing from channel")
	stopChan <- true
	delete(c.stopSubscribers, path)
} // SubscribeCryptellationBacktestsOrdersListResponse will subscribe to new messages from 'cryptellation.backtests.orders.list.response' channel.
// Callback function 'fn' will be called each time a new message is received.
// The 'done' argument indicates when the subscription is canceled and can be
// used to clean up resources.
func (c *ClientController) SubscribeCryptellationBacktestsOrdersListResponse(fn func(msg BacktestsOrdersListResponseMessage, done bool)) error {
	// Get channel path
	path := "cryptellation.backtests.orders.list.response"

	// Check if there is already a subscription
	_, exists := c.stopSubscribers[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", ErrAlreadySubscribedChannel, path)
		c.LogError(log.Context{Action: path}, err.Error())
		return err
	}

	// Subscribe to broker channel
	c.LogInfo(log.Context{Action: path, Operation: "subscribe"}, "Subscribing to channel")
	msgs, stop, err := c.brokerController.Subscribe(path)
	if err != nil {
		c.LogError(log.Context{Action: path, Operation: "subscribe"}, err.Error())
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			um, open := <-msgs

			// Process message
			msg, err := newBacktestsOrdersListResponseMessageFromUniversalMessage(um)
			if err != nil {
				c.LogError(log.Context{Action: path, Operation: "subscribe", Message: msg}, err.Error())
			}

			// Send info if message is correct or susbcription is closed
			if err == nil || !open {
				c.LogInfo(log.Context{Action: path, Operation: "subscribe", Message: msg}, "Received new message")
				fn(msg, !open)
			}

			// If subscription is closed, then exit the function
			if !open {
				return
			}
		}
	}()

	// Add the stop channel to the inside map
	c.stopSubscribers[path] = stop

	return nil
}

// UnsubscribeCryptellationBacktestsOrdersListResponse will unsubscribe messages from 'cryptellation.backtests.orders.list.response' channel
func (c *ClientController) UnsubscribeCryptellationBacktestsOrdersListResponse() {
	// Get channel path
	path := "cryptellation.backtests.orders.list.response"

	// Get stop channel
	stopChan, exists := c.stopSubscribers[path]
	if !exists {
		return
	}

	// Stop the channel and remove the entry
	c.LogInfo(log.Context{Action: path, Operation: "unsubscribe"}, "Unsubscribing from channel")
	stopChan <- true
	delete(c.stopSubscribers, path)
} // SubscribeCryptellationBacktestsSubscribeResponse will subscribe to new messages from 'cryptellation.backtests.subscribe.response' channel.
// Callback function 'fn' will be called each time a new message is received.
// The 'done' argument indicates when the subscription is canceled and can be
// used to clean up resources.
func (c *ClientController) SubscribeCryptellationBacktestsSubscribeResponse(fn func(msg BacktestsSubscribeResponseMessage, done bool)) error {
	// Get channel path
	path := "cryptellation.backtests.subscribe.response"

	// Check if there is already a subscription
	_, exists := c.stopSubscribers[path]
	if exists {
		err := fmt.Errorf("%w: %q channel is already subscribed", ErrAlreadySubscribedChannel, path)
		c.LogError(log.Context{Action: path}, err.Error())
		return err
	}

	// Subscribe to broker channel
	c.LogInfo(log.Context{Action: path, Operation: "subscribe"}, "Subscribing to channel")
	msgs, stop, err := c.brokerController.Subscribe(path)
	if err != nil {
		c.LogError(log.Context{Action: path, Operation: "subscribe"}, err.Error())
		return err
	}

	// Asynchronously listen to new messages and pass them to app subscriber
	go func() {
		for {
			// Wait for next message
			um, open := <-msgs

			// Process message
			msg, err := newBacktestsSubscribeResponseMessageFromUniversalMessage(um)
			if err != nil {
				c.LogError(log.Context{Action: path, Operation: "subscribe", Message: msg}, err.Error())
			}

			// Send info if message is correct or susbcription is closed
			if err == nil || !open {
				c.LogInfo(log.Context{Action: path, Operation: "subscribe", Message: msg}, "Received new message")
				fn(msg, !open)
			}

			// If subscription is closed, then exit the function
			if !open {
				return
			}
		}
	}()

	// Add the stop channel to the inside map
	c.stopSubscribers[path] = stop

	return nil
}

// UnsubscribeCryptellationBacktestsSubscribeResponse will unsubscribe messages from 'cryptellation.backtests.subscribe.response' channel
func (c *ClientController) UnsubscribeCryptellationBacktestsSubscribeResponse() {
	// Get channel path
	path := "cryptellation.backtests.subscribe.response"

	// Get stop channel
	stopChan, exists := c.stopSubscribers[path]
	if !exists {
		return
	}

	// Stop the channel and remove the entry
	c.LogInfo(log.Context{Action: path, Operation: "unsubscribe"}, "Unsubscribing from channel")
	stopChan <- true
	delete(c.stopSubscribers, path)
}

// PublishCryptellationBacktestsAccountsListRequest will publish messages to 'cryptellation.backtests.accounts.list.request' channel
func (c *ClientController) PublishCryptellationBacktestsAccountsListRequest(msg BacktestsAccountsListRequestMessage) error {
	// Convert to UniversalMessage
	um, err := msg.toUniversalMessage()
	if err != nil {
		return err
	}

	// Get channel path
	path := "cryptellation.backtests.accounts.list.request"

	// Publish on event broker
	c.LogInfo(log.Context{Action: path, Operation: "publish", Message: msg}, "Publishing to channel")
	return c.brokerController.Publish(path, um)
}

// PublishCryptellationBacktestsAdvanceRequest will publish messages to 'cryptellation.backtests.advance.request' channel
func (c *ClientController) PublishCryptellationBacktestsAdvanceRequest(msg BacktestsAdvanceRequestMessage) error {
	// Convert to UniversalMessage
	um, err := msg.toUniversalMessage()
	if err != nil {
		return err
	}

	// Get channel path
	path := "cryptellation.backtests.advance.request"

	// Publish on event broker
	c.LogInfo(log.Context{Action: path, Operation: "publish", Message: msg}, "Publishing to channel")
	return c.brokerController.Publish(path, um)
}

// PublishCryptellationBacktestsCreateRequest will publish messages to 'cryptellation.backtests.create.request' channel
func (c *ClientController) PublishCryptellationBacktestsCreateRequest(msg BacktestsCreateRequestMessage) error {
	// Convert to UniversalMessage
	um, err := msg.toUniversalMessage()
	if err != nil {
		return err
	}

	// Get channel path
	path := "cryptellation.backtests.create.request"

	// Publish on event broker
	c.LogInfo(log.Context{Action: path, Operation: "publish", Message: msg}, "Publishing to channel")
	return c.brokerController.Publish(path, um)
}

// PublishCryptellationBacktestsOrdersCreateRequest will publish messages to 'cryptellation.backtests.orders.create.request' channel
func (c *ClientController) PublishCryptellationBacktestsOrdersCreateRequest(msg BacktestsOrdersCreateRequestMessage) error {
	// Convert to UniversalMessage
	um, err := msg.toUniversalMessage()
	if err != nil {
		return err
	}

	// Get channel path
	path := "cryptellation.backtests.orders.create.request"

	// Publish on event broker
	c.LogInfo(log.Context{Action: path, Operation: "publish", Message: msg}, "Publishing to channel")
	return c.brokerController.Publish(path, um)
}

// PublishCryptellationBacktestsOrdersListRequest will publish messages to 'cryptellation.backtests.orders.list.request' channel
func (c *ClientController) PublishCryptellationBacktestsOrdersListRequest(msg BacktestsOrdersListRequestMessage) error {
	// Convert to UniversalMessage
	um, err := msg.toUniversalMessage()
	if err != nil {
		return err
	}

	// Get channel path
	path := "cryptellation.backtests.orders.list.request"

	// Publish on event broker
	c.LogInfo(log.Context{Action: path, Operation: "publish", Message: msg}, "Publishing to channel")
	return c.brokerController.Publish(path, um)
}

// PublishCryptellationBacktestsSubscribeRequest will publish messages to 'cryptellation.backtests.subscribe.request' channel
func (c *ClientController) PublishCryptellationBacktestsSubscribeRequest(msg BacktestsSubscribeRequestMessage) error {
	// Convert to UniversalMessage
	um, err := msg.toUniversalMessage()
	if err != nil {
		return err
	}

	// Get channel path
	path := "cryptellation.backtests.subscribe.request"

	// Publish on event broker
	c.LogInfo(log.Context{Action: path, Operation: "publish", Message: msg}, "Publishing to channel")
	return c.brokerController.Publish(path, um)
}

// WaitForCryptellationBacktestsAccountsListResponse will wait for a specific message by its correlation ID
//
// The pub function is the publication function that should be used to send the message
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message
func (cc *ClientController) WaitForCryptellationBacktestsAccountsListResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func() error) (BacktestsAccountsListResponseMessage, error) {
	// Get channel path
	path := "cryptellation.backtests.accounts.list.response"

	// Subscribe to broker channel
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()}, "Wait for response")
	msgs, stop, err := cc.brokerController.Subscribe(path)
	if err != nil {
		cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
		return BacktestsAccountsListResponseMessage{}, err
	}

	// Close subscriber on leave
	defer func() { stop <- true }()

	// Execute publication
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: publishMsg, CorrelationID: publishMsg.CorrelationID()},
		"Sending request",
	)
	if err := pub(); err != nil {
		return BacktestsAccountsListResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case um, open := <-msgs:
			// Get new message
			msg, err := newBacktestsAccountsListResponseMessageFromUniversalMessage(um)
			if err != nil {
				cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
			}

			// If valid message with corresponding correlation ID, return message
			if err == nil && publishMsg.CorrelationID() == msg.CorrelationID() {
				cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: msg, CorrelationID: msg.CorrelationID()},
					"Received expected message",
				)
				return msg, nil
			} else if !open { // If message is invalid or not corresponding and the subscription is closed, then return error
				cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
					"Channel closed before getting message",
				)
				return BacktestsAccountsListResponseMessage{}, ErrSubscriptionCanceled
			}
		case <-ctx.Done(): // Return error if context is done
			cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
				"Context done before getting message",
			)
			return BacktestsAccountsListResponseMessage{}, ErrContextCanceled
		}
	}
}

// WaitForCryptellationBacktestsAdvanceResponse will wait for a specific message by its correlation ID
//
// The pub function is the publication function that should be used to send the message
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message
func (cc *ClientController) WaitForCryptellationBacktestsAdvanceResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func() error) (BacktestsAdvanceResponseMessage, error) {
	// Get channel path
	path := "cryptellation.backtests.advance.response"

	// Subscribe to broker channel
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()}, "Wait for response")
	msgs, stop, err := cc.brokerController.Subscribe(path)
	if err != nil {
		cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
		return BacktestsAdvanceResponseMessage{}, err
	}

	// Close subscriber on leave
	defer func() { stop <- true }()

	// Execute publication
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: publishMsg, CorrelationID: publishMsg.CorrelationID()},
		"Sending request",
	)
	if err := pub(); err != nil {
		return BacktestsAdvanceResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case um, open := <-msgs:
			// Get new message
			msg, err := newBacktestsAdvanceResponseMessageFromUniversalMessage(um)
			if err != nil {
				cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
			}

			// If valid message with corresponding correlation ID, return message
			if err == nil && publishMsg.CorrelationID() == msg.CorrelationID() {
				cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: msg, CorrelationID: msg.CorrelationID()},
					"Received expected message",
				)
				return msg, nil
			} else if !open { // If message is invalid or not corresponding and the subscription is closed, then return error
				cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
					"Channel closed before getting message",
				)
				return BacktestsAdvanceResponseMessage{}, ErrSubscriptionCanceled
			}
		case <-ctx.Done(): // Return error if context is done
			cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
				"Context done before getting message",
			)
			return BacktestsAdvanceResponseMessage{}, ErrContextCanceled
		}
	}
}

// WaitForCryptellationBacktestsCreateResponse will wait for a specific message by its correlation ID
//
// The pub function is the publication function that should be used to send the message
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message
func (cc *ClientController) WaitForCryptellationBacktestsCreateResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func() error) (BacktestsCreateResponseMessage, error) {
	// Get channel path
	path := "cryptellation.backtests.create.response"

	// Subscribe to broker channel
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()}, "Wait for response")
	msgs, stop, err := cc.brokerController.Subscribe(path)
	if err != nil {
		cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
		return BacktestsCreateResponseMessage{}, err
	}

	// Close subscriber on leave
	defer func() { stop <- true }()

	// Execute publication
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: publishMsg, CorrelationID: publishMsg.CorrelationID()},
		"Sending request",
	)
	if err := pub(); err != nil {
		return BacktestsCreateResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case um, open := <-msgs:
			// Get new message
			msg, err := newBacktestsCreateResponseMessageFromUniversalMessage(um)
			if err != nil {
				cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
			}

			// If valid message with corresponding correlation ID, return message
			if err == nil && publishMsg.CorrelationID() == msg.CorrelationID() {
				cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: msg, CorrelationID: msg.CorrelationID()},
					"Received expected message",
				)
				return msg, nil
			} else if !open { // If message is invalid or not corresponding and the subscription is closed, then return error
				cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
					"Channel closed before getting message",
				)
				return BacktestsCreateResponseMessage{}, ErrSubscriptionCanceled
			}
		case <-ctx.Done(): // Return error if context is done
			cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
				"Context done before getting message",
			)
			return BacktestsCreateResponseMessage{}, ErrContextCanceled
		}
	}
}

// WaitForCryptellationBacktestsOrdersCreateResponse will wait for a specific message by its correlation ID
//
// The pub function is the publication function that should be used to send the message
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message
func (cc *ClientController) WaitForCryptellationBacktestsOrdersCreateResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func() error) (BacktestsOrdersCreateResponseMessage, error) {
	// Get channel path
	path := "cryptellation.backtests.orders.create.response"

	// Subscribe to broker channel
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()}, "Wait for response")
	msgs, stop, err := cc.brokerController.Subscribe(path)
	if err != nil {
		cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
		return BacktestsOrdersCreateResponseMessage{}, err
	}

	// Close subscriber on leave
	defer func() { stop <- true }()

	// Execute publication
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: publishMsg, CorrelationID: publishMsg.CorrelationID()},
		"Sending request",
	)
	if err := pub(); err != nil {
		return BacktestsOrdersCreateResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case um, open := <-msgs:
			// Get new message
			msg, err := newBacktestsOrdersCreateResponseMessageFromUniversalMessage(um)
			if err != nil {
				cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
			}

			// If valid message with corresponding correlation ID, return message
			if err == nil && publishMsg.CorrelationID() == msg.CorrelationID() {
				cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: msg, CorrelationID: msg.CorrelationID()},
					"Received expected message",
				)
				return msg, nil
			} else if !open { // If message is invalid or not corresponding and the subscription is closed, then return error
				cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
					"Channel closed before getting message",
				)
				return BacktestsOrdersCreateResponseMessage{}, ErrSubscriptionCanceled
			}
		case <-ctx.Done(): // Return error if context is done
			cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
				"Context done before getting message",
			)
			return BacktestsOrdersCreateResponseMessage{}, ErrContextCanceled
		}
	}
}

// WaitForCryptellationBacktestsOrdersListResponse will wait for a specific message by its correlation ID
//
// The pub function is the publication function that should be used to send the message
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message
func (cc *ClientController) WaitForCryptellationBacktestsOrdersListResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func() error) (BacktestsOrdersListResponseMessage, error) {
	// Get channel path
	path := "cryptellation.backtests.orders.list.response"

	// Subscribe to broker channel
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()}, "Wait for response")
	msgs, stop, err := cc.brokerController.Subscribe(path)
	if err != nil {
		cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
		return BacktestsOrdersListResponseMessage{}, err
	}

	// Close subscriber on leave
	defer func() { stop <- true }()

	// Execute publication
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: publishMsg, CorrelationID: publishMsg.CorrelationID()},
		"Sending request",
	)
	if err := pub(); err != nil {
		return BacktestsOrdersListResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case um, open := <-msgs:
			// Get new message
			msg, err := newBacktestsOrdersListResponseMessageFromUniversalMessage(um)
			if err != nil {
				cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
			}

			// If valid message with corresponding correlation ID, return message
			if err == nil && publishMsg.CorrelationID() == msg.CorrelationID() {
				cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: msg, CorrelationID: msg.CorrelationID()},
					"Received expected message",
				)
				return msg, nil
			} else if !open { // If message is invalid or not corresponding and the subscription is closed, then return error
				cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
					"Channel closed before getting message",
				)
				return BacktestsOrdersListResponseMessage{}, ErrSubscriptionCanceled
			}
		case <-ctx.Done(): // Return error if context is done
			cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
				"Context done before getting message",
			)
			return BacktestsOrdersListResponseMessage{}, ErrContextCanceled
		}
	}
}

// WaitForCryptellationBacktestsSubscribeResponse will wait for a specific message by its correlation ID
//
// The pub function is the publication function that should be used to send the message
// It will be called after subscribing to the channel to avoid race condition, and potentially loose the message
func (cc *ClientController) WaitForCryptellationBacktestsSubscribeResponse(ctx context.Context, publishMsg MessageWithCorrelationID, pub func() error) (BacktestsSubscribeResponseMessage, error) {
	// Get channel path
	path := "cryptellation.backtests.subscribe.response"

	// Subscribe to broker channel
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()}, "Wait for response")
	msgs, stop, err := cc.brokerController.Subscribe(path)
	if err != nil {
		cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
		return BacktestsSubscribeResponseMessage{}, err
	}

	// Close subscriber on leave
	defer func() { stop <- true }()

	// Execute publication
	cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: publishMsg, CorrelationID: publishMsg.CorrelationID()},
		"Sending request",
	)
	if err := pub(); err != nil {
		return BacktestsSubscribeResponseMessage{}, err
	}

	// Wait for corresponding response
	for {
		select {
		case um, open := <-msgs:
			// Get new message
			msg, err := newBacktestsSubscribeResponseMessageFromUniversalMessage(um)
			if err != nil {
				cc.LogError(log.Context{Action: path, Operation: "wait-for"}, err.Error())
			}

			// If valid message with corresponding correlation ID, return message
			if err == nil && publishMsg.CorrelationID() == msg.CorrelationID() {
				cc.LogInfo(log.Context{Action: path, Operation: "wait-for", Message: msg, CorrelationID: msg.CorrelationID()},
					"Received expected message",
				)
				return msg, nil
			} else if !open { // If message is invalid or not corresponding and the subscription is closed, then return error
				cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
					"Channel closed before getting message",
				)
				return BacktestsSubscribeResponseMessage{}, ErrSubscriptionCanceled
			}
		case <-ctx.Done(): // Return error if context is done
			cc.LogError(log.Context{Action: path, Operation: "wait-for", CorrelationID: publishMsg.CorrelationID()},
				"Context done before getting message",
			)
			return BacktestsSubscribeResponseMessage{}, ErrContextCanceled
		}
	}
}
