CREATE DATABASE IF NOT EXISTS backtests;
CREATE DATABASE IF NOT EXISTS candlesticks;
CREATE DATABASE IF NOT EXISTS exchanges;
CREATE DATABASE IF NOT EXISTS indicators;
CREATE DATABASE IF NOT EXISTS ticks;
