services:  

  mongo:
    image: mongo:7-jammy
    ports:
      - 127.0.0.1:27017:27017
    expose:
      - 27017
    networks:
      - cryptellation

  postgresql:
    image: postgres:17.4-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: cryptellation
    networks:
      - cryptellation

  temporal:
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:1.25
    ports:
      - 7233:7233
    expose:
      - 7233
    volumes:
      - ./temporal:/etc/temporal/config/dynamicconfig
    networks:
      - cryptellation
  temporal-ui:
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.31.2
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - cryptellation
  
  uptrace-otelcollector:
    image: otel/opentelemetry-collector-contrib:0.110.0
    depends_on:
      - uptrace
    volumes:
      - ./uptrace/otel-collector.yaml:/etc/otelcol/config.yaml
    expose:
      - 4317
      - 4318
    networks:
      - cryptellation
  uptrace-clickhouse:
    image: clickhouse/clickhouse-server:23.7
    environment:
      CLICKHOUSE_DB: uptrace
    expose:
      - 8123
      - 9000
    networks:
      - cryptellation
  uptrace:
    image: uptrace/uptrace:1.6.2
    ports:
      - 4318:4318
    depends_on:
      - postgresql
      - uptrace-clickhouse
    volumes:
      - ./uptrace/uptrace.yaml:/etc/uptrace/uptrace.yml
    expose:
      - 4317
      - 4318
    networks:
      - cryptellation

networks:
  cryptellation:
