apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-worker
  name: {{ .Release.Name }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      annotations:
        {{if (.Values.debug).forceDeployment }}timestamp: {{ now | quote }}{{end}}
      labels:
        app: {{ .Release.Name }}-worker
    spec:
      initContainers:
      - name: sql-migrations
        image: {{ ((.Values.services).worker).image.repository | default "lerenn/cryptellation" }}:{{ ((.Values.services).worker).image.tag | default (printf "v%s" .Chart.AppVersion) }}
        imagePullPolicy: {{ ((.Values.services).worker).image.pullPolicy | default "Always" }}
        command: ["worker", "database", "migrate"]
        env:
        # SQL
        - name: "SQL_DSN"
          valueFrom:
            configMapKeyRef:
              key: sql.dsn
              name: cryptellation-credentials
      containers:
      - name: worker
        image: {{ ((.Values.services).worker).image.repository | default "lerenn/cryptellation" }}:{{ ((.Values.services).worker).image.tag | default (printf "v%s" .Chart.AppVersion) }}
        imagePullPolicy: {{ ((.Values.services).worker).image.pullPolicy | default "Always" }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ (((.Values.services).worker).health).port | default 9000 }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ (((.Values.services).worker).health).port | default 9000 }}
        env:
        # Binance
        - name: "CRYPTELLATION_BINANCE_API_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.api_key
              name: cryptellation-credentials
        - name: "CRYPTELLATION_BINANCE_SECRET_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.secret_key
              name: cryptellation-credentials
        # Health
        - name: "HEALTH_PORT"
          valueFrom:
            configMapKeyRef:
              key:  worker.health.port
              name: cryptellation-config
        # SQL
        - name: "SQL_DSN"
          valueFrom:
            configMapKeyRef:
              key: sql.dsn
              name: cryptellation-credentials
        # Opentelemetry
        - name: "OPENTELEMETRY_GRPC_ENDPOINT"
          valueFrom:
            configMapKeyRef:
              key: opentelemetry.grpc.endpoint
              name: cryptellation-credentials
        # Temporal
        - name: "TEMPORAL_ADDRESS"
          valueFrom:
            configMapKeyRef:
              key: temporal.address
              name: cryptellation-credentials
        resources: {}
status: {}
