DOCKER_IMAGE := lerenn/cryptellation-indicators

PROJECT_ROOT_PATH := ../..

DAGGER_MODULE_PATH := .

include $(PROJECT_ROOT_PATH)/tools/make/dagger.mk
include $(PROJECT_ROOT_PATH)/tools/make/docker.mk
include $(PROJECT_ROOT_PATH)/tools/make/go.mk
include $(PROJECT_ROOT_PATH)/tools/make/help.mk
include $(PROJECT_ROOT_PATH)/tools/make/service.mk